# Generated by Django 5.0.1 on 2024-01-09 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cvgenerator', '0003_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='image',
        ),
    ]
